version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .local.env
    volumes:
      - type: bind
        source: .
        target: /code
      - static_volume:/code/static
    command: bash -c "python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &
      gunicorn --workers 4 --bind :7000 --timeout 500 --reload configuration.wsgi"
    expose:
      - 7000

  postgres:
    container_name: postgres
    image: postgres:12.4
    expose:
      - 6543
    ports:
      - 6543:6543
    command: -p 6543
    env_file:
      - .local.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    image: nginx:1.19.4
    ports:
      - "7000:80"
    volumes:
      - .:/code
      - static_volume:/code/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static_volume:
  postgres_data: